tpnsDatabase:
  build: ../applicationserver/wildfly/	
  name: tpnsDatabase  
  ports:
  - "5432:5432"
  environment:
    POSTGRES_PASSWORD: 123456
    TPNS_PASS: 123456
tpnsAppServer:
  build: ../database/postgres/	
  name: tpnsDatabase    
  ports:
  - "127.0.0.1:8080:8080"
  links:
  - tpnsDatabase:postgres    
